# Generated by Django 4.2.5 on 2023-10-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
