# Generated by Django 4.2.5 on 2023-10-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0002_delete_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
