# Generated by Django 4.2.5 on 2023-10-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0003_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='publication date'),
        ),
    ]
