# Generated by Django 4.2.5 on 2023-10-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0004_alter_book_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now=True, verbose_name='publication date'),
        ),
    ]
