# Generated by Django 4.2.6 on 2023-10-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('average_rating', models.FloatField(verbose_name='average rating')),
                ('isbn', models.CharField(max_length=150, verbose_name='isbn')),
                ('isbn13', models.CharField(max_length=150, verbose_name='isbn 13')),
                ('language_code', models.CharField(max_length=10, verbose_name='language code')),
                ('num_pages', models.IntegerField(verbose_name='number of pages')),
                ('rating_count', models.BigIntegerField(verbose_name='rating count')),
                ('text_review_count', models.BigIntegerField(verbose_name='text review count')),
                ('publication_date', models.DateField(auto_now=True, verbose_name='publication date')),
                ('publisher', models.CharField(max_length=150, verbose_name='publisher')),
            ],
        ),
    ]
