# Generated by Django 4.2.6 on 2023-12-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_section', '0002_alter_review_book'),
        ('bookmark', '0002_alter_bookmark_book'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
