# Generated by Django 4.2.6 on 2023-12-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('author', models.TextField(blank=True, max_length=255, null=True, verbose_name='author')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='average rating')),
                ('isbn', models.TextField(blank=True, max_length=150, null=True, verbose_name='isbn')),
                ('isbn13', models.TextField(blank=True, max_length=150, null=True, verbose_name='isbn 13')),
                ('language_code', models.TextField(blank=True, max_length=10, null=True, verbose_name='language code')),
                ('num_pages', models.IntegerField(blank=True, null=True, verbose_name='number of pages')),
                ('rating_count', models.BigIntegerField(blank=True, null=True, verbose_name='rating count')),
                ('text_review_count', models.BigIntegerField(blank=True, null=True, verbose_name='text review count')),
                ('publication_date', models.DateField(auto_now=True, null=True, verbose_name='publication date')),
                ('publisher', models.TextField(blank=True, max_length=150, null=True, verbose_name='publisher')),
            ],
        ),
    ]
